#!/bin/bash

if [ $# -eq 0 ] || [ $1 == "-help"  ]; then
  echo "$./process_run [saveFile] [TimeWindow] [evtDir]"
  echo ""
  
  exit 1
fi;

SaveFile=$1

DIR=$(pwd)
TIMEWINDOW=100
DATA_DIR=data/data/Mar10-04

fileList=$(\ls $DIR/${DATA_DIR}/*.evt.to.fsu.100)
numFile=$(\ls -1 $DIR/${DATA_DIR}/*.evt.to.fsu.100 | wc -l)

echo "##############################################"
echo "number of files : "$numFile
echo "##############################################"

./armory/to2root $SaveFile 100  $fileList


exit 0


    
